<?php echo $this->doctype(); ?>
<!DOCTYPE html>
<html lang="pt-BR">
    <?php echo $this->partial('head.phtml', 'application'); ?>
    <body>
        <?php echo $this->partial('header.phtml', 'application'); ?>
        <div class="main">
            <?php echo $this->content; ?>
            <?php echo $this->inlineScript() ?>
        </div>
        <?php echo $this->partial('footer.phtml', 'application'); ?>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="<?php echo $this->basePath() ?>/assets/js/bootstrap.min.js"></script>
    </body>
</html>