<div class="feature">
    <div class="feature-inner">
        <div class="container">
            <div class="col-md-6 caption">
                <h1>
                    keep calm <strong>and make</strong> 
                    <span> a <strong> dream come</strong> true </span>
                </h1>
                <h2>
                    Criamos oportunidades para as pessoas realizarem 
                    seus sonhos de educação em todo mundo
                </h2>
                <a class="btn btn-lg btn-primary" href="<?php echo $this->basePath() ?>/sign-up" role="button">Conte seu sonho</a>
            </div>
            <div id="myCarousel" class="carousel col-md-6 slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="item active">					
                        <div class="carousel-caption">
                            <p>Quando eu conheci a Education
                               Dream eu tive certeza que aqui
                               eu ia conseguir realizar meu
                               sonho de estudar no exterior
                            </p>
                            <span>
                                <img src="<?php echo $this->basePath() ?>/assets/images/attest-1.png" alt="Attest">
                                <h3>Edmilson Rodrigues</h3>
                                <h4>Formou em Empreendedorismo nos EUA</h4>
                            </span>
                        </div>
                    </div>
                    <div class="item">
                        <div class="carousel-caption">
                            <p>Quando eu conheci a Education
                               Dream eu tive certeza que aqui
                               eu ia conseguir realizar meu
                               sonho de estudar no exterior
                            </p>
                            <span>
                                <img src="<?php echo $this->basePath() ?>/assets/images/attest-2.png" alt="Attest" />
                                <h3>
                                    Tulio Braga
                                </h3>
                                <h4>
                                    Engenheiro de computação
                                </h4>
                            </span>
                        </div>
                    </div>
                    <div class="item">
                        <div class="carousel-caption">
                            <p>Quando eu conheci a Education
                               Dream eu tive certeza que aqui
                               eu ia conseguir realizar meu
                               sonho de estudar no exterior
                            </p>
                            <span>
                                <img src="<?php echo $this->basePath() ?>/assets/images/attest-3.png" alt="Attest">
                                <h3>Lucas Azevedo</h3>
                                <h4>UI/UX Designer and Developer</h4>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>