<div class="feature">
    <div class="feature-inner">
        <div class="container">
            <div class="col-md-6 caption">
                <h1>
                    keep calm <strong>and make</strong> 
                    <span> a <strong> dream come</strong> true </span>
                </h1>
                <h2>
                    Criamos oportunidades para as pessoas realizarem 
                    seus sonhos de educação em todo mundo
                </h2>
                <a class="btn btn-lg btn-primary" href="<?php echo $this->basePath() ?>/sign-up" role="button">Conte seu sonho</a>
            </div>
            <div id="myCarousel" class="carousel col-md-6 slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="item active">					
                        <div class="carousel-caption">
                            <p>Quando eu conheci a Education
                             Dream eu tive certeza que aqui
                             eu ia conseguir realizar meu
                             sonho de estudar no exterior
                         </p>
                         <span>
                            <img src="<?php echo $this->basePath() ?>/assets/images/attest-1.png" alt="Attest">
                            <h3>Edmilson Rodrigues</h3>
                            <h4>Formou em Empreendedorismo nos EUA</h4>
                        </span>
                    </div>
                </div>
                <div class="item">
                    <div class="carousel-caption">
                        <p>Quando eu conheci a Education
                         Dream eu tive certeza que aqui
                         eu ia conseguir realizar meu
                         sonho de estudar no exterior
                     </p>
                     <span>
                        <img src="<?php echo $this->basePath() ?>/assets/images/attest-2.png" alt="Attest" />
                        <h3>
                            Tulio Braga
                        </h3>
                        <h4>
                            Engenheiro de computação
                        </h4>
                    </span>
                </div>
            </div>
            <div class="item">
                <div class="carousel-caption">
                    <p>Quando eu conheci a Education
                     Dream eu tive certeza que aqui
                     eu ia conseguir realizar meu
                     sonho de estudar no exterior
                 </p>
                 <span>
                    <img src="<?php echo $this->basePath() ?>/assets/images/attest-3.png" alt="Attest">
                    <h3>Lucas Azevedo</h3>
                    <h4>UI/UX Designer and Developer</h4>
                </span>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>






<div class="main">
    <div class="container home">

        <div class="row">
            <div class="col-lg-6 text-center">
                <img src="./layouts/about.png" alt="" class="img-about">
            </div>
            <div class="col-lg-6">
                <div class="col-md-12 text-center">
                    <img src="./layouts/people.png" alt="" class="img-people">
                </div>
                <div class="col-md-12 text-center">
                    <img src="./layouts/angel.png" alt="" class="img-angel">
                </div>
                <div class="col-md-12 text-center">
                    <img src="./layouts/founding.png" alt="" class="img-founding">
                </div>
            </div>
        </div>
        
        <hr />

        <div class="row">
            <div class="col-lg-12 text-center">
                <img src="./layouts/interrest.png" alt="" class="img-interrest">
            </div>
        </div>



        


    </div>
</div>



<div class="row do">
    <div class="col-md-6 text-center ">
        <img src="./layouts/do.png" alt="" class="img-do">
    </div>
    <div class="col-md-6">
        <img src="./layouts/photo.png" alt="" class="img-photo">
    </div>


</div>


<div class="blog">
    <div class="container home">

        <div class="row">
            <div class="col-lg-12 text-center">
                <img src="./layouts/blog.png" alt="" class="img-blog">
            </div>
            <div class="col-lg-12">
                <div class="col-md-6 text-center">
                    <img src="./layouts/blog1.png" alt="" class="img-blog1">
                </div>
                <div class="col-md-6 text-center">
                    <img src="./layouts/blog2.png" alt="" class="img-blog2">
                </div>
                
            </div>
        </div>

    </div>
</div>

