<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/form-signup.css');
?>

<div class="main">

<div class="container sign">
    <form method="post" action="?">
   
    <div class="col-md-6 col-md-offset-3">
        <h2>Selecione o seu tipo de usuário.</h2>
        <div class="btn-group" data-toggle="buttons" style="width:320px; margin: 0 auto;display: block;clear: both;float: none; overflow: hidden;">
            <label class="btn btn-signup active">
                <input type="radio" value='S' name="role" id="optSonhador" autocomplete="off" checked> Sonhador
            </label>
            <label class="btn btn-signup">
                <input type="radio" value='M' name="role" id="optMentor" autocomplete="off"> Mentor
            </label>
            <label class="btn btn-signup">
                <input type="radio" value='O' name="role" id="optOrganizacao" autocomplete="off"> Organização
            </label>
        </div>
    </div>

    <div class="col-md-6 col-md-offset-3">
        <h2>Para começar o cadastro, você precisa conectar com o Facebook.
        </h2>
        <a href="#" class="btn btn-lg btn-facebook btn-primary btn-signup">

        <b>facebook</b>
            Conectar </a>
    </div>
    <div class="col-md-6 col-md-offset-3">
        <p class='or'>
            <span>ou</span>
        </p>

        <h2>Criar uma conta.
        </h2>
            <div class="form-group">
                <label for="exampleInputName1">Seu nome *</label>
                <input name="text" type="name" class="form-control" id="exampleInputName1" placeholder="Digite seu nome">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Seu e-mail *</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Digite seu email">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Digite sua senha *</label>
                <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Digite sua senha">
            </div>

            <button type="submit" class="btn btn-lg btn-big btn-primary btn-signup">Cadastrar </button>
        <p>Por favor, preencha todos os campos obrigatórios (*).</p>
    </div>
    </form>
</div>
</div>