

<div class="row search2">
    <div class="col-md-12 text-center ">
        <img src="./layouts/search-2.png" alt="" class="search_png">
    </div>
</div>



<div class="main">
    <div class="container home">

        <div class="row">
            <h2>
<?php 
$container = new \Zend\Session\Container('login');
$user = $container->user;
var_dump($user);
if($user) {
?>
</h2>
            <div class="col-md-4 text-center">
                <img src="./layouts/s1.png" alt="" class="s_png">
            </div>
            <div class="col-md-4 text-center">
                <img src="./layouts/s2.png" alt="" class="s_png">
            </div>
            <div class="col-md-4 text-center">
                <img src="./layouts/s3.png" alt="" class="s_png">
            </div>
            <div class="col-md-4 text-center">
                <img src="./layouts/s5.png" alt="" class="s_png">
            </div>
            <div class="col-md-4 text-center">
                <img src="./layouts/s6.png" alt="" class="s_png">
            </div>
            <div class="col-md-4 text-center">
                <img src="./layouts/s4.png" alt="" class="s_png">
            </div>


            <div class="col-md-12 text-center">
                <img src="./layouts/bt-more.png" alt="">
            </div>

        </div>
        


        <div class="row">

            <div class="col-md-12 text-center">
                <img src="./layouts/fazer.png" alt="" class="fazer_png">
            </div>


            <div class="col-md-4 text-center">
                <img src="./layouts/s7.png" alt="" class="ss_png">
            </div>
            <div class="col-md-4 text-center">
                <img src="./layouts/s8.png" alt="" class="ss_png">
            </div>
            <div class="col-md-4 text-center">
                <img src="./layouts/s9.png" alt="" class="ss_png">
            </div>
            

            <div class="col-md-12 text-center">
                <img src="./layouts/bt-more.png" alt="">
            </div>

        </div>
        }
?>        

        <hr />


        <div class="row">
            <div class="col-lg-12 text-center">
                <img src="./layouts/interrest.png" alt="" class="img-interrest">
            </div>
        </div>



        


    </div>
</div>


