<footer>
    <div class="nav-footer">
        <div class="container">
            <div class="row">
                <div class="buttons">
                    <a class="btn btn-lg btn-primary btn-login" href="#" role="button">Entrar</a>
                    <a class="btn btn-lg btn-primary btn-signup" href="#" role="button">Quero estudar</a>
                </div>
                <div class="col-md-9 visible-md visible-lg footer-menu">
                    <div class="col-md-2">
                        <h3>Sobre</h3>
                        <ul>
                            <li><a href="#">Quem somos</a></li>
                            <li><a href="#">Projetos</a></li>
                            <li><a href="#">Parceiros</a></li>
                            <li><a href="#">Trabalhe conosco</a></li>
                        </ul>
                    </div>
                    <div class="col-md-2">
                        <h3>Sonhadores</h3>
                        <ul>
                            <li><a href="#">O que é?</a></li>
                            <li><a href="#">Quero estudar no exterior</a></li>
                        </ul>
                    </div>
                    <div class="col-md-2">
                        <h3>Mentores</h3>
                        <ul>
                            <li><a href="#">Como funciona</a></li>
                            <li><a href="#">Quero ser mentor</a></li>
                        </ul>
                    </div>
                    <div class="col-md-2">
                        <h3>Ajude um Nerd</h3>
                        <ul>
                            <li><a href="#">Perguntas frequentes</a></li>
                        </ul>
                    </div>
                    <div class="col-md-2">
                        <h3><a href="#">Fazejamento</a></h3>
                    </div>
                    <div class="col-md-2">
                        <h3><a href="#">Blog </a></h3>
                    </div>
                </div>
                <div class="col-md-3 visible-md visible-lg">
                    <div class="fb-like-box" data-href="https://www.facebook.com/EducationDream" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-social">
        <div class="container">
            <div class="row">
                <div class="logos col-md-6 col-md-offset-3">
                    <div class="col-md-4">
                        <img src="<?php echo $this->basePath() ?>/assets/images/logo-1.jpg" alt="">
                    </div>
                    <div class="col-md-4">
                        <img src="<?php echo $this->basePath() ?>/assets/images/logo-2.jpg" alt="">
                    </div>
                    <div class="col-md-4">
                        <img src="<?php echo $this->basePath() ?>/assets/images/logo-3.jpg" alt="">
                    </div>
                </div>
            </div>

            <p>&copy; 2014 Company, Inc. &middot; 
                <a href="#">Privacy</a> &middot; <a href="#">Terms</a>
            </p>
            <a class="back-top" href="#">
                <img src="<?php echo $this->basePath() ?>/assets/images/arrow-top.png" alt="Attest">
            </a>
        </div>
    </div>
</footer>