<div class="navbar-wrapper">
    <div class="container">
        <nav class="navbar navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Education Dream</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="#"><img src="<?php echo $this->basePath() ?>/assets/images/home.png" alt="Home"></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sobre <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Quem somos</a></li>
                                <li><a href="#">Projetos</a></li>
                                <li><a href="#">Parceiros</a></li>
                            </ul>
                        </li>
                        <li><a href="#sonhadores">Sonhadores</a></li>
                        <li><a href="#mentores">Mentores</a></li>
                        <li><a href="#ajude-um-nerd">Ajude um Nerd</a></li>
                        <li><a href="#fazejamento">Fazejamento</a></li>
                        <li><a href="#blog">Blog</a></li>
                        <li><a class="btn btn-lg btn-primary btn-login" href="<?php echo $this->basePath() ?>/login" role="button">Entrar</a></li>
                        <li><a class="btn btn-lg btn-primary btn-signup" href="<?php echo $this->basePath() ?>/sign-up" role="button">Conte seu sonho</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>